apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    name: webapp
  
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 80
      targetPort: 80
  type: LoadBalancer
